version: "3.8"

services:
  pyrestmutex:
    image: dtsurk0v/pyrestmutex:latest
    ports:
      - "3114:8000"
    volumes:
      - ./data:/app/data
    environment:
      - DB_PATH=/app/data/locks.db
